version: "3.3"
services:
  store:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/store:/usr/src/app'
    ports:
      - "8080:8080"
    links:
      - "db"
      - "shopping_cart"
      - "user"

  shopping_cart:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/shopping_cart:/usr/src/app'
    links:
      - "db"
    expose:
      - "8080"

  user:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/user:/usr/src/app'
    links:
      - "db"
    expose:
      - "8080"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=NotMyBestIdea
    expose:
      - "5432"
        # ports:
        #- "5432:5432"
