version: "3.3"
services:
  store:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/store:/usr/src/app'
    expose:
      - "8080"
    links:
      - "toxiproxy"

  shopping_cart:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/shopping_cart:/usr/src/app'
    links:
      - "db"
    expose:
      - "8080"

  user:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/user:/usr/src/app'
    links:
      - "db"
    expose:
      - "8080"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=NotMyBestIdea
    expose:
      - "5432"

  toxiproxy:
    image: shopify/toxiproxy
    command: -host=0.0.0.0 -config=/root/config/toxiproxy.json
    ports:
      - "8474:8474"
      - "8080:8080"
    volumes:
      - ./toxiproxy:/root/config
    links:
      - "db"
      - "shopping_cart"
      - "user"
    expose:
      - "5432"
      - "8080" # store
      - "8081" # shopping_cart
      - "8082" # user