version: "3.3"
services:
  store:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/store:/usr/src/app'
    expose:
      - "8080"
    links:
      - "toxiproxy"

  shopping_cart:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './services/shopping_cart:/usr/src/app'
    environment:
      - DB=toxiproxy
    depends_on:
      - toxiproxy
    expose:
      - "8080"

  user:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - DB=toxiproxy
    depends_on:
      - toxiproxy
    volumes:
      - './services/user:/usr/src/app'
    expose:
      - "8080"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=NotMyBestIdea
    expose:
      - "5432"

  toxiproxy:
    image: shopify/toxiproxy
    command: -host=0.0.0.0 -config=/root/config/toxiproxy.json
    ports:
      - "8474:8474"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./toxiproxy:/root/config
    depends_on:
      - db
    expose:
      - "5432"
      - "8080" # store
      - "8081" # shopping_cart
      - "8082" # user