---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Shopping cart microservice"
paths:
  /cart/{userId}:
    get:
      tags:
        - "cart"
      operationId: "get_cart_by_user_id"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cart"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Cart not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
    post:
      tags:
        - "cart"
      operationId: "create_cart_for_user"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Cart not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
    delete:
      tags:
        - "cart"
      operationId: "empty_cart"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
  /cart/{userId}/checkout:
    post:
      tags:
        - "cart"
      operationId: "checkout_cart"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
  /cart/{userId}/article:
    post:
      tags:
        - "cart"
      operationId: "add_article_to_cart"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "article"
        required: true
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
  /cart/{userId}/article/{articleId}:
    delete:
      tags:
        - "cart"
      operationId: "remove_article_from_cart"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "articleId"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.cart_controller"
definitions:
  Cart:
    type: "object"
    properties:
      articles:
        type: "array"
        items:
          $ref: "#/definitions/Item"
      abandoned:
        type: "boolean"
      complete:
        type: "boolean"
        default: false
    example:
      abandoned: true
      complete: false
      articles:
      - quantity: 0
        articleId: 6
      - quantity: 0
        articleId: 6
  Item:
    type: "object"
    properties:
      quantity:
        type: "integer"
      articleId:
        type: "integer"
    example:
      quantity: 0
      articleId: 6
